<?php

/**
 * @file
 * Hook implementations.
 */


define('ARCHIDORA_RDF_URI', 'http://islandora.ca/archivematica#');


/**
 * Implements hook_menu().
 */
function archidora_menu() {
  $items = array();

  $items['admin/islandora/archidora'] = array(
    'title' => 'Archivematica Integration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('archidora_admin_form'),
    'access arguments' => array('administer archivematica integration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/admin.form.inc',
  );
  $items['islandora/object/%islandora_object/manage/archivematica'] = array(
    'title' => 'Archivematica',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('archidora_object_status_form', 2),
    'access arguments' => array('administer archivematica integration'),
    'file' => 'includes/object.form.inc',
  );
  return $items;
}

/**
 * Implements hook_islandora_derivative().
 */
function archidora_islandora_derivative(AbstractObject $object) {
  $mod_path = drupal_get_path('module', 'archidora');

  $items = array();

  module_load_include('inc', 'archidora', 'includes/utilities');
  $skip_models = archidora_skip_content_models();

  if (count(array_intersect($object->models, $skip_models)) === 0 && archidora_get_parent($object)) {
    $items[] = array(
      'source_dsid' => NULL,
      'destination_dsid' => NULL,
      'weight' => '1000',
      'function' => array(
        'archidora_derivative_callback',
      ),
      'file' => "$mod_path/includes/derivatives.inc",
    );
  }

  return $items;
}

/**
 * Implements hook_permission().
 */
function archidora_permission() {
  return array(
    'administer archivematica integration' => array(
      'title' => t('Administer Archivematica Integration'),
      'description' => t('Administer settings for Archivematica integration and display the Archivematica tab on objects.'),
    ),
  );
}
